addr = "localhost:8080"
root = "public"

ssl = false
ssl_cert_file = ""
ssl_key_file = ""

access_log = true
access_log_file = ""
access_log_file_mode = 644

gzip = true
gzip_level = 1

[log]
    file = ""
    file_mode = 644

[db]
    # MySQL
    #driver = "mysql"
    #dsn = "username:password@(localhost)/dbname?charset=utf8mb4&parseTime=True&loc=Local"
    
    # SQL Server
    #driver = "mssql"
    #dsn = "sqlserver://username:password@localhost:1433?database=dbname"
    
    # SQLite 3
    #driver = "sqlite3"
    #dsn = "/tmp/clevergo.db"
    
    # PostgreSQL
    #driver = "postgres"
    #dsn = "host=localhost port=port user=username dbname=dbname password=password"

[session]
    lifetime = 3600 # in seconds
    idle_timeout = 1200 # in seconds
    cookie_name = "session_id"
    cookie_domain = ""
    cookie_path = "/"
    cookie_http_only = true
    cookie_persist = true
    cookie_secure = true # disable it in local develop environment.
    cookie_same_site = 3 # see http.SameSite

[csrf]
    key = "AUTH_KEY"

[view]
    directory = "themes/frontend"
    cache = true
    layouts = [
    ]
    [view.static] # mapping from path to static directory.

[adminView]
    directory = "themes/backend"
    cache = true
    layouts = [
    ]
    [adminView.static] # mapping from path to static directory.

[i18n]
    directory = "translations"
    fallback = "en"
    param = "lang"
    cookie_param = "lang"

[mail]
    host = ""
    port = 25
    username = ""
    password = ""

[captcha]
    height = 50
    width = 120

[migration]
    db = "dbname"
    driver = "mysql"
    dsn = "user:password@tcp(localhost:3306)/dbname?multiStatements=true"
    path = "migrations/mysql"

[params]
    title = "CleverGo"
    subtitle = "CleverGo Application Project Template"
    since = 2020
    titleSeparator = "-"
    backendTitle = "CleverGo Console"
    version = "v0.0.1"