[cors]
    allowed_origins = []
    allowed_methods = ["GET", "POST", "PUT", "DELETE"]
    allowed_headers = ["Authorization", "Content-Type"]
    max_age = 600
    allow_credentials = false
    debug = false